# Theme
general.import = [ "theme.toml" ]

[window]
title = "Terminal"
dynamic_title = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Extrabold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 10.0

[mouse]
hide_when_typing = true
