# Theme
general.import = [ "theme.toml" ]

[window]
title = "Terminal"
dynamic_title = true
startup_mode = "Maximized"

[font]
normal.family = "JetBrains Mono Nerd Font"
normal.style = "Bold" 
italic.family = "JetBrains Mono Nerd Font"
italic.style = "Bold Italic"  
bold.family = "JetBrains Mono Nerd Font"
bold.style = "Bold"
bold_italic.family = "JetBrains Mono Nerd Font"
bold_italic.style = "Bold Italic"
size = 10.0

[mouse]
hide_when_typing = true
