[colors.primary]
background = "0x1C2433"
foreground = "0xD0D7E4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.search.focused_match]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.selection]
text = "CellForeground"
background = "0x3B465B"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "0x646C7A"
red = "0xff738a"
green = "0x3cec85"
yellow = "0xeaCD61"
blue = "0x69c3ff"
magenta = "0xf38cec"
cyan = "0x22ecdb"
white = "0xD0D7E4"

[colors.bright]
black = "0x646C7A"
red = "0xff738a"
green = "0x3cec85"
yellow = "0xeaCD61"
blue = "0x69c3ff"
magenta = "0xf38cec"
cyan = "0x22ecdb"
white = "0xD0D7E4"
